name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install libc6-dev
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build wasmlib
        run: |
          rustup target add wasm32-wasip1
          cd wasmlib
          cargo build --target=wasm32-wasip1 --release
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
